name: "Update Release Notes"
description: "Update Release Notes Action"
author: "Shane"
branding:
  icon: "activity"
  color: "yellow"

inputs:
  location:
    description: "Location to place notes"
    required: false
    default: "tail"
  delimiter:
    description: "String where to insert notes"
    required: false
  remove:
    description: "Remove delimiter after insert"
    required: false
    default: "false"
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"
  token:
    description: "GitHub Token"
    required: false
    default: ${{ github.token }}
  type:
    description: "Update Type"
    required: false
  issues:
    description: "Issues Link"
    required: false
    default: "true"
  tags:
    description: "Actions Tags"
    required: false

outputs:
  body:
    description: "Full Release Notes Body"
  notes:
    description: "Generated Release Notes"

runs:
  using: "node20"
  main: "dist/index.js"
