name: "Update Release Notes"
description: "Update Release Notes Action"
author: "Shane"
branding:
  icon: "activity"
  color: "yellow"

inputs:
  location:
    description: "Location to place notes"
    default: "tail"
  delimiter:
    description: "String where to insert notes"
  remove:
    description: "Remove delimiter after insert"
    default: "false"
  update:
    description: "Update Release Notes"
    default: "true"
  summary:
    description: "Add Summary to Job"
    default: "true"
  token:
    description: "GitHub Token"
    default: ${{ github.token }}
  type:
    description: "Update Type"
  issues:
    description: "Issues Link"
    default: "true"
  tags:
    description: "Actions Tags"

outputs:
  body:
    description: "Full Release Notes Body"
  notes:
    description: "Generated Release Notes"

runs:
  using: "node24"
  main: "dist/index.js"
