name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Update Tags"
        id: tags
        uses: cssnr/update-version-tags-action@v1

      - name: "Update Release Notes"
        run: |
          echo tags: ${{ steps.tags.outputs.tags }}
